endpoints:
  auth: "https://napi.unext.jp/1/auth/login"
  account: "https://napi.unext.jp/2/user/account/get"
  search: "https://napi.unext.jp/1/cmscommon/freeword/video"
  stage: "https://napi.unext.jp/1/cmsuser/stage"
  movie: "https://napi.unext.jp/1/cmsuser/episode/current"
  relation: "https://napi.unext.jp/1/cmsuser/titledetail/relation"
  episode: "https://napi.unext.jp/1/cmsuser/episode"
  playlist: "https://napi.unext.jp/3/cmsuser/playlisturl/file"

device:
  user_agent: "U-NEXT TV App Android16 5.61.0 AOSP TV"
